const jobsData = [
  {
    url: 'https://acme.corp/jobs/front-end-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Development',
    date: '2023-03-20',
    employer: 'Acme Corporation',
    facebook: 'https://www.facebook.com/acme',
    twitter: 'https://twitter.com/acme',
    experienceYears: 5,
    expertiseLevel: 'Intermediate',
    description:
      "As a front-end developer at Acme Corporation, you will be responsible for building and maintaining the company's website and web applications.",
    title: 'Front-end Developer',
    contractType: 'Fulltime',
    keywords: [
      'front-end development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Vue.js',
      'Git',
      'version control',
    ],
    location: { city: 'New York', country: 'United States' },
    overview:
      'Acme Corporation is seeking a talented front-end developer to join our growing team.',
    requiredSkills: [
      'Proficiency in HTML, CSS, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Vue.js.',
      'Experience with Git and version control.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's website and web applications.",
      'Maintain and improve existing code.',
      'Collaborate with designers and back-end developers to implement new features.',
      'Write clean, modular, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
    ],
    salary: { max: 80000, min: 50000 },
  },
  {
    url: 'https://omega.corp/jobs/full-stack-developer',
    benefits: [
      'Competitive salary and benefits package with annual bonuses.',
      'Flexible work hours and options to work remotely from anywhere in the world.',
      'Opportunities for career growth and advancement.',
      'Collaborative and fun work environment with regular team events.',
    ],
    category: 'Development',
    date: '2023-03-27',
    employer: 'Omega Corp',
    facebook: 'https://www.facebook.com/omegacorp',
    twitter: 'https://twitter.com/omegacorp',
    experienceYears: 7,
    expertiseLevel: 'Senior',
    description:
      "As a full-stack developer at Omega Corp, you will be responsible for developing and maintaining the company's web applications and services.",
    title: 'Full-stack Developer',
    contractType: 'Fulltime',
    keywords: [
      'full-stack development',
      'web development',
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Node.js',
      'MongoDB',
      'AWS',
    ],
    location: { city: 'San Francisco', country: 'United States' },
    overview:
      'Omega Corp is looking for a highly skilled full-stack developer to join our team.',
    requiredSkills: [
      'Expertise in HTML, CSS, and JavaScript.',
      'Strong experience with modern web development frameworks such as React and Node.js.',
      'Experience with MongoDB and AWS.',
      'Excellent problem-solving and debugging skills.',
      'Exceptional communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop new features for the company's web applications and services.",
      'Maintain and improve existing code.',
      'Collaborate with designers and other developers to implement new features.',
      'Write well-documented, modular, and scalable code.',
      'Optimize web applications for performance and scalability.',
    ],
    salary: { max: 120000, min: 80000 },
  },
  {
    url: 'https://jobseeker.com/jobs/front-end-developer',
    benefits: [
      'Generous salary and benefits package.',
      'Flexible work hours and work-from-home options.',
      'Opportunities for learning and career growth.',
      'Fun and collaborative work environment.',
      'Free snacks and beverages.',
      'Gym membership allowance.',
      'Company outings and team-building events.',
    ],
    category: 'Development',
    date: '2023-03-27',
    employer: 'ABC Corp',
    facebook: 'https://www.facebook.com/abccorp',
    twitter: 'https://twitter.com/abccorp',
    experienceYears: 3,
    expertiseLevel: 'Junior',
    description:
      "ABC Corp is seeking a talented front-end developer to join our team and help us build beautiful and responsive web applications.",
    title: 'Front-end Developer',
    contractType: 'Part-Time',
    keywords: [
      'front-end development',
      'web development',
      'HTML5',
      'CSS3',
      'JavaScript',
      'React',
      'Angular',
      'Git',
      'version control',
      'Agile development',
    ],
    location: { city: 'San Francisco', country: 'United States' },
    overview:
      'Join ABC Corp, a rapidly growing startup, and help us shape the future of the web!',
    requiredSkills: [
      'Strong proficiency in HTML5, CSS3, and JavaScript.',
      'Experience with modern front-end frameworks such as React or Angular.',
      'Experience with Git and version control.',
      'Ability to write clean, well-documented, and maintainable code.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Design and develop new features for our web applications.",
      'Collaborate with product managers and designers to create intuitive and user-friendly interfaces.',
      'Write clean, maintainable, and well-documented code.',
      'Optimize web pages for maximum speed and scalability.',
      'Participate in code reviews and ensure code quality and consistency.',
      'Stay up-to-date with the latest web development trends and best practices.',
    ],
    salary: { max: 100000, min: 60000 },
  },
  {
    url: 'https://example.com/jobs/backend-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career growth.',
      'Collaborative and inclusive team environment.',
    ],
    category: 'Development',
    date: '2023-03-27',
    employer: 'Innovative Solutions, Inc.',
    facebook: 'https://www.facebook.com/innovativesolutions',
    twitter: 'https://twitter.com/innovativesolutions',
    experienceYears: 3,
    expertiseLevel: 'Intermediate',
    description:
      "As a backend developer at Innovative Solutions, you'll be part of a team responsible for building and maintaining the company's internal and customer-facing web applications.",
    title: 'Backend Developer',
    contractType: 'Full-time',
    keywords: [
      'backend development',
      'web development',
      'Python',
      'Java',
      'REST APIs',
      'SQL',
      'NoSQL',
      'Docker',
      'Kubernetes',
    ],
    location: { city: 'San Francisco', country: 'United States' },
    overview:
      'Innovative Solutions is looking for a talented backend developer to join our team and help us build the next generation of web applications.',
    requiredSkills: [
      'Proficiency in Python or Java.',
      'Experience building REST APIs and working with SQL or NoSQL databases.',
      'Experience with Docker and Kubernetes.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
    ],
    responsibilities: [
      "Develop and maintain backend APIs for internal and customer-facing web applications.",
      'Collaborate with front-end developers to implement new features and improve existing ones.',
      'Work with the infrastructure team to ensure that applications are scalable, reliable, and performant.',
      'Write clean, modular, and well-documented code.',
      'Participate in code reviews and provide feedback to other developers on the team.',
    ],
    salary: { max: 100000, min: 70000 },
  },
  {
    url: 'https://irrelephantfilms.com/jobs/video-editor',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Friendly and supportive work environment.',
    ],
    category: 'Media',
    date: '2023-03-27',
    employer: 'Irrelephant Films',
    facebook: 'https://www.facebook.com/irrelephantfilms',
    twitter: 'https://twitter.com/irrelephantfilms',
    experienceYears: 3,
    expertiseLevel: 'Intermediate',
    description:
      "As a video editor at Irrelephant Films, you will be responsible for editing and producing high-quality video content for our clients.",
    title: 'Video Editor',
    contractType: 'Fulltime',
    keywords: [
      'video editing',
      'motion graphics',
      'color grading',
      'Adobe Premiere',
      'After Effects',
      'DaVinci Resolve',
      'storytelling',
      'client management',
    ],
    location: { city: 'Los Angeles', country: 'United States' },
    overview:
      'Irrelephant Films is seeking a talented video editor to join our growing team.',
    requiredSkills: [
      'Proficiency in Adobe Premiere, After Effects, and DaVinci Resolve.',
      'Experience with motion graphics and color grading.',
      'Excellent storytelling skills.',
      'Ability to manage client expectations and timelines.',
      'Strong communication and collaboration skills.',
    ],
    responsibilities: [
      'Edit and produce high-quality video content for clients.',
      'Collaborate with our team to develop creative concepts and execute on them.',
      'Manage multiple projects and deadlines simultaneously.',
      'Stay up-to-date with industry trends and tools.',
      'Provide feedback to clients and incorporate their feedback into the final product.',
    ],
    salary: { max: 70000, min: 45000 },
  },
  {
    url: 'https://grumbletech.io/jobs/full-stack-developer',
    benefits: [
      'Competitive salary and benefits package.',
      'Flexible work hours and remote work options.',
      'Opportunities for professional development and career advancement.',
      'Fully stocked kitchen with snacks and beverages.',
      'Weekly team building activities and happy hours.',
    ],
    category: 'Development',
    date: '2023-03-27',
    employer: 'GrumbleTech',
    facebook: 'https://www.facebook.com/grumbletech',
    twitter: 'https://twitter.com/grumbletech',
    experienceYears: 3,
    expertiseLevel: 'Intermediate',
    description:
      "GrumbleTech is looking for a full-stack developer with a passion for creating delightful and innovative experiences. We're a dynamic and fast-growing startup that's pushing the boundaries of what's possible in the world of technology.",
    title: 'Full-Stack Developer',
    contractType: 'Fulltime',
    keywords: [
      'full-stack development',
      'web development',
      'JavaScript',
      'React',
      'Node.js',
      'MongoDB',
      'AWS',
      'Git',
      'version control',
    ],
    location: { city: 'San Francisco', country: 'United States' },
    overview:
      'GrumbleTech is seeking a talented full-stack developer to join our growing team.',
    requiredSkills: [
      'Proficiency in JavaScript and Node.js.',
      'Experience with modern front-end frameworks such as React.',
      'Experience with server-side web frameworks such as Express.',
      'Experience with database technologies such as MongoDB.',
      'Familiarity with cloud computing platforms such as AWS.',
      'Strong problem-solving and debugging skills.',
      'Excellent communication and collaboration skills.',
      'Ability to grumble creatively and effectively.',
    ],
    responsibilities: [
      'Create and maintain high-quality web applications and services.',
      'Collaborate with designers and product managers to create delightful user experiences.',
      'Grumble about challenging technical problems and work with your team to find creative solutions.',
      'Write clean, efficient, and maintainable code.',
      'Help establish and maintain best practices for software development at GrumbleTech.',
      'Participate in code reviews and provide constructive feedback.',
      'Mentor and guide junior members of the team.',
      'Occasionally grumble about non-technical challenges (such as the weather or the quality of the office coffee).',
    ],
    salary: { max: 120000, min: 80000 },
  },
]

export default jobsData;